version: '3'
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./:/var/www/laravel-feature
  nginx:
    image: nginx:1.20.2
    container_name: nginx
    ports:
      - 8090:80
    volumes:
      - ./:/var/www/laravel-feature
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/laravel-feature
    depends_on:
      - app
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_features
      MYSQL_USER: db-user1
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/setup.sh:/setup.sh
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmy-admin
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
        MINIO_ENDPOINT: http://localhost:9001/dashboard
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9999 --console-address :9001"
    volumes:
        - ./docker/minio/data:/export
    ports:
      - "9000:9999"
      - "9001:9001"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
    volumes:
      - "./docker/mhsendmail:/usr/local/bin/mhsendmail"
